goldenoaklibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
]

goldenoaklibrary/goldenoaklibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
]

goldenoaklibrary/catalog/models.py
import uuid

from django.db import models
from django.urls import reverse # Used in get_absolute_url() to get URL for specified ID

from django.db.models import UniqueConstraint # Constrains fields to unique values
from django.db.models.functions import Lower # Returns lower cased value of field

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a particular genre instance."""
        return reverse('genre-detail', args=[str(self.id)])

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='genre_name_case_insensitive_unique',
                violation_error_message = "Genre already exists (case insensitive match)"
            ),
        ]
        verbose_name = 'genre'
        verbose_name_plural = 'genres'


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)"
    )

    def get_absolute_url(self):
        """Returns the url to access a particular language instance."""
        return reverse('language-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='language_name_case_insensitive_unique',
                violation_error_message = "Language already exists (case insensitive match)"
            ),
        ]
        verbose_name = 'language'
        verbose_name_plural = 'languages'


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        'Author', 
        on_delete=models.RESTRICT, 
        null=True
    )
    # Foreign Key used because book can only have one author, but authors can have multiple books.
    # Author as a string rather than object because it hasn't been declared yet in file.

    summary = models.TextField(
        max_length=1000, 
        help_text="Enter a brief description of the book"
    )
    isbn = models.CharField(
        'ISBN', 
        max_length=13,
        unique=True,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'
    )

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    
    class Meta:
        verbose_name = 'book'
        verbose_name_plural = 'books'

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ','.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(
        primary_key=True, 
        default=uuid.uuid4,
        help_text="Unique ID for this particular book across whole library"
    )
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability'
    )

    class Meta:
        ordering = ['due_back']
        verbose_name = 'book instance'
        verbose_name_plural = 'book instances'

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    
    
class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
        verbose_name = 'author'
        verbose_name_plural = 'authors'

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'
    

goldenoaklibrary/catalog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Book, Author, BookInstance, Genre

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    """Generic class-based view for a list of books."""
    model = Book
    paginate_by = 10
    

class BookDetailView(generic.DetailView):
    """Generic class-based view for a single book."""
    model = Book
    
    

goldenoaklibrary/catalog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="headerbar">
        <div class="headerbar__logo">Golden Oak Library</div>
        <div class="headerbar__account">
            <!-- Placeholder login button -->
            <a href="" class="headerbar__btn">Login</a>
        </div>
    </header>
    <div class="app-container">
        <nav class="sidebar">
            <ul class="sidebar__nav">
                <li class="sidebar__item">
                    <a href="{% url 'index' %}" class="sidebar__link">🏠 Home</a>
                </li>
                <li class="sidebar__item">
                    <a href="{% url 'books' %}" class="sidebar__link">📚 All Books</a>
                </li>
                <li class="sidebar__item">
                    <a href="" class="sidebar__link">👨‍🏫 All Authors</a>
                </li>
            </ul>
        </nav>
        <main class="content">
            {% block content %}
            {% endblock content %} 
        </main>
        {% block pagination %}
            {% if is_paginated %}
                <aside class="pagination">
                    {% if page_obj.has_previous %}
                        <a
                            href="{{ request.path }}?page={{ page_obj.previous_page_number }}"
                            class="btn"
                            role="button"
                        >Previous</a>
                    {% endif %}
                    <span class="pagination__current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                        <a
                            href="{{ request.path }}?page={{ page_obj.next_page_number }}"
                            class="btn"
                            role="button"
                        >Next</a>
                    {% endif %}
                </aside>
            {% endif %}
        {% endblock pagination %}
    </div>
    <footer class="footerbar">
        <p class="footerbar__text">Website created by Gage O'Laughlin</p>
    </footer>
</body>
</html>

goldenoaklibrary/catalog/templates/catalog/book_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title">Title: {{ book.title }}</h1>

    <dl class="detailed-list">
        <div class="detailed-list__item">
            <dt class="detailed-list__term">Author</dt>
            <dd class="detailed-list__desc">
                <a href="" class="link">{{ book.author }}</a>
            </dd>
        </div>
        <div class="detailed-list__item">
            <dt class="detailed-list__term">Genre</dt>
            <dd class="detailed-list__desc">{{ book.genre.all|join:", " }}</dd>
        </div>
        <div class="detailed-list__item">
            <dt class="detailed-list__term">ISBN</dt>
            <dd class="detailed-list__desc">{{ book.isbn }}</dd>
        </div>
    </dl>

    <h2 class="heading">Book Summary</h2>
    <p class="text">{{ book.summary }}</p>

    <h2 class="heading">Copies</h2>
    <table class="table">
        <thead class="table__head">
            <tr class="table__row">
                <th scope="col" class="table__header">ID</th>
                <th scope="col" class="table__header">Imprint</th>
                <th scope="col" class="table__header">Status</th>
                <th scope="col" class="table__header">Due Back</th>
            </tr>
        </thead>
        <tbody class="table__body">
            {% for copy in book.bookinstance_set.all %}
                <tr class="table__row">
                    <td class="table__data">{{ copy.id }}</td>
                    <td class="table__data">{{ copy.imprint }}</td>
                    <td class="table__data
                            {% if copy.status == 'a' %}
                                table__data--success
                            {% elif copy.status == 'm' %}
                                table__data--danger
                            {% else %}
                                table__data--warning
                            {% endif %}"
                    >{{ copy.get_status_display }}</td>
                    <td class="table__data">
                        {% if copy.status != 'a' %}
                            <span>{{ copy.due_back }}</span>
                        {% else %}
                            <span>N/A</span>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

goldenoaklibrary/catalog/templates/catalog/book_list.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title">Book List</h1>
    {% if book_list %}
        <ul class="list">
            {% for book in book_list %}
                <li class="list__item">
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                    ({{book.author}})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock content %}

goldenoaklibrary/catalog/templates/index.html
{% extends 'base.html' %}

{% block title %}Home - Golden Oak Library{% endblock title %}

{% block content %}
    <h1 class="title">Welcome to Golden Oak Library</h1>
    <section class="section">
        <h2 class="section__title">Record</h2>
        <p class="text">The library has the following record counts</p>

        <ul>
            <li>Books: {{ num_books }}</li>
            <li>Copies: {{ num_instances }}</li>
            <li>Copies Available: {{ num_instances_available }}</li>
            <li>Authors: {{ num_authors }}</li>
        </ul>
    </section>
{% endblock content %}